export const SET_SESSION = 'SET_SESSION'
export const SET_CART = 'SET_CART'
export const SET_MERCHANT_ON_CART = 'SET_MERCHANT_ON_CART'

export const SET_CURRENT_GEOLOCATION = 'SET_CURRENT_GEOLOCATION'
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION'
export const SET_DESTINATION_LOCATION = 'SET_DESTINATION_LOCATION'

export const SET_CURRENT_GEOCODE = 'SET_CURRENT_GEOCODE'
export const SET_SELECTED_GEOCODE = 'SET_SELECTED_GEOCODE'
export const SET_DESTINATION_GEOCODE = 'SET_DESTINATION_GEOCODE'
export const SET_SELECTED_PLACE_INFO = 'SET_SELECTED_PLACE_INFO'
export const SET_DESTINATION_PLACE_INFO = 'SET_DESTINATION_PLACE_INFO'

export const SET_PERMISSION_ANDROID = 'SET_PERMISSION_ANDROID'
export const SET_PERMISSION_IOS = 'SET_PERMISSION_IOS'