export const SET_SESSION = 'SET_SESSION'
export const SET_CART = 'SET_CART'
export const SET_MERCHANT_ON_CART = 'SET_MERCHANT_ON_CART'

export const SET_CURRENT_GEOLOCATION = 'SET_CURRENT_GEOLOCATION'
export const SET_SELECTED_GEOLOCATION = 'SET_SELECTED_GEOLOCATION'

export const SET_CURRENT_GEOCODE = 'SET_CURRENT_GEOCODE'
export const SET_SELECTED_GEOCODE = 'SET_SELECTED_GEOCODE'

export const SET_PERMISSION_ANDROID = 'SET_PERMISSION_ANDROID'
export const SET_PERMISSION_IOS = 'SET_PERMISSION_IOS'
export const SET_ACCURACY = 'SET_ACCURACY'